# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - branchtest

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'      

      - name: Install npm packages - server
        run: |
          cd server
          npm install       
      
      - name: Install npm packages, build then copy files - client
        run: |
          cd public
          npm install
          npm run build
          cp -r ./build ../server
            
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: branchtest
          path: server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: branchtest

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C8A25D3A34E048E28D552CA4017301F6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_68502F96A2D046A58BC6D036AAC94BCB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EB1684E5415E4976A0BA9A265B5586A4 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'branchtest'
          slot-name: 'Production'
          package: .
          
